#!/bin/sh
period=3

BAT_PERCENT_SIZE=4

SVNSEG='/home/victor/.local/lib/dwmstatus/seven-seg'
DATA_DIR='/home/victor/.cache/padd_fetch'
[ -d $DATA_DIR ] || exit

[ -f $DATA_DIR/battery ] && BAT=$( cat $DATA_DIR/battery )
[ -f $DATA_DIR/pinging_status ] && [ $(cat $DATA_DIR/pinging_status) -eq 1 ] && PING='^c#00ff00^^r3,7,5,1^^r4,9,3,1^^r5,11,1,1^^d^'
#[[ -f $DATA_DIR/pinging_status ]] && [[ $(cat $DATA_DIR/pinging_status) -eq 2 ]] && PING='^c#ff0000^^r3,9,5,1^^r3,13,5,1^^r4,7,1,9^^r6,7,1,9^^d^' 
[ -f $DATA_DIR/pinging_status ] && [ $(cat $DATA_DIR/pinging_status) -eq 2 ] && PING='^c#ff0000^^r2,2,2,19^^r8,2,2,19^' 

GRAPHIC='^r0,2,1,19^^r10,2,1,19^^r1,1,9,1^^r1,21,9,1^^r4,2,3,1^'$PING'^f11^'

H=$( echo $BAT'*20' | bc 2> /dev/null )
BAT_GRAPHIC='^r4,'$(echo "22-"$H | bc 2> /dev/null )',2,'$H'^^r2,2,2,1^^r2,12,2,1^^r2,21,4,1^^r3,2,1,20^^f9^'
#BAT_GRAPHIC='^r2,'$(echo "22-"$H | bc)',3,'$H'^^r2,2,1,20^^r5,2,1,20^^r2,1,4,1^^f8^^d^'
BAT100=$(echo $BAT"*100" | bc 2> /dev/null | cut -d '.' -f 1)
#BAT_SVNSEG=$($SVNSEG $(echo $BAT100 | cut -c 1) $BAT_PERCENT_SIZE 0 1)$($SVNSEG $(echo $BAT100 | cut -c 2) $BAT_PERCENT_SIZE 7 1)$($SVNSEG $(echo $BAT100 | cut -c 3) $BAT_PERCENT_SIZE 14 1)
BAT_SVNSEG=$($SVNSEG $BAT100 $BAT_PERCENT_SIZE 0 1)

echo ' '$GRAPHIC$BAT_GRAPHIC$BAT_SVNSEG^f3^^d^
